//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSchoolEntities : DbContext
    {
        public dbSchoolEntities()
            : base("name=dbSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDocent> tblDocents { get; set; }
        public virtual DbSet<tblKlasgroep> tblKlasgroeps { get; set; }
        public virtual DbSet<tblRichting> tblRichtings { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
    }
}
