//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDocent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocent()
        {
            this.tblKlasgroeps = new HashSet<tblKlasgroep>();
        }
    
        public int docent_id { get; set; }
        [Required]
        [StringLength(60)]
        public string voornaam { get; set; }
        [Required]
        [StringLength(60)]
        public string achternaam { get; set; }
        [Required]
        [StringLength(60)]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKlasgroep> tblKlasgroeps { get; set; }
    }
}
