//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStudent
    {
        public int student_id { get; set; }
        [Required]
        [StringLength(60)]
        public string voornaam { get; set; }
        [Required]
        [StringLength(60)]
        public string achternaam { get; set; }
        [Required]
        [StringLength(60)]
        public string email_ouder { get; set; }
        [Range(0, 10)]
        public Nullable<double> rapport_wiskunde { get; set; }
        [Range(0, 10)]
        public Nullable<double> rapport_frans { get; set; }
        [Range(0, 10)]
        public Nullable<double> rapport_engels { get; set; }
        [Range(0, 10)]
        public Nullable<double> rapport_sport { get; set; }
        [Range(0, 10)]
        public Nullable<double> rapport_biologie { get; set; }
        public Nullable<int> klasgroep_id { get; set; }
    
        public virtual tblKlasgroep tblKlasgroep { get; set; }
    }
}
